# Generated by Django 3.2.3 on 2021-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210531_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='point',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
