# Generated by Django 3.2.3 on 2021-06-11 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_auto_20210606_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='product.comment'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='user',
            field=models.ManyToManyField(related_name='user_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='product.product'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(null=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
