# Generated by Django 3.2.3 on 2021-06-12 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_auto_20210611_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(null=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
