# Generated by Django 3.2.3 on 2021-06-14 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
