# Generated by Django 3.2.3 on 2021-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210519_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
